import numpy.typing as ntp
import pandas as pd
from typing import Any, Literal, Optional, Sequence, overload

stopwords: set[str]

def mean(items: Sequence) -> float: ...
def cross_softmax(one: ntp.NDArray, two: ntp.NDArray,
                  temp1: float = ..., temp2: float = ...): ...


def slope_coefficient(one: ntp.NDArray, two: ntp.NDArray) -> float: ...
@overload
def get_concreteness_df(_format: Literal['df'] = 'df') -> pd.DataFrame: ...
@overload
def get_concreteness_df(_format: Literal['dict']) -> dict[str, float]: ...

@overload
def get_imageability_df(_format: Literal['df'] = "df") -> pd.DataFrame: ...
@overload
def get_imageability_df(_format: Literal['dict']) -> dict: ...


@overload
def get_freq_df(_format: Literal["df"]) -> pd.DataFrame: ...
@overload
def get_freq_df(_format: Literal["dict"]) -> dict[str, float]: ...

@overload
def get_freq_df(_format: str) -> Any: ...

